# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Deploy to IPFS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Upload to IPFS
        id: upload
        uses: aquiladev/ipfs-action@v0.1.2-alpha.0
        with:
          # directory path to upload
          path: ./build
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: 843dea1cc2e721163c20a5c876b5b155f7f3aa75
          body: |
            Deployed at: https://cloudflare-ipfs.com/ipfs/${{ steps.upload.outputs.hash }}/#/
          position: 1

        
